name: Testing the Self-hosted Runner
on:
  workflow_dispatch:

jobs:
  Testing:
    runs-on: self-hosted
    steps:
      - name: Echo Contest
        run: |
          echo OK
          sleep 15s
  


